overhaul internal path logic

diff --git a/pgpbackup-encrypt b/pgpbackup-encrypt
--- a/pgpbackup-encrypt
+++ b/pgpbackup-encrypt
@@ -53,7 +53,7 @@ fi
 function hashName {
     local fileName=$1
 
-    echo "${_arg_emails[0]}-$(basename "$fileName")" | shasum -a 256 | cut -f1 -d " "
+    echo "${_arg_recipient[0]}-$(basename "$fileName")" | shasum -a 256 | cut -f1 -d " "
 }
 
 function encryptFile {
@@ -82,8 +82,9 @@ function checkFiles {
     while read i
     do
         if [[ "$i" != *decrypt.sh ]] && [[ "$i" != *pgpbackup-decrypt ]]; then
-            if [ ! -f "$outFolder/$i.gpg" ]; then
-                encryptFile "$i" "$outFolder/${i#"$inFolder"}"
+            local outFile="$outFolder/${i#"$inFolder"}.gpg"
+            if [ ! -f "$outFile" ]; then
+                encryptFile "$i" "$outFolder${i#"$inFolder"}"
             fi
 
             local filesize=$(stat --printf="%s" "$i")
@@ -95,27 +96,27 @@ function checkFiles {
 function handleDir {
     local depth=$1
     local path=$2
+    local first=$3
 
     # Create necessary folders
-    if [ "$path" = "$inFolder" ]; then
+    if [ "$first" = "on" ]; then
         mkdir -p "$outFolder"
         cp "$inFolder/decrypt.sh" "$outFolder/decrypt.sh" 2> /dev/null
         cp "$inFolder/pgpbackup-decrypt" "$outFolder/pgpbackup-decrypt" 2> /dev/null
     fi
 
     if [ $depth -eq 0 ]; then
-        path="$path/."
-        path=${path#"$inFolder/"}
-        if [ "$path" = "." ]; then
+        if [ "$first" = "on" ]; then
             folderPath="."
             folderName="backup"
         else
-            folderPath="$(dirname "${path%"/."}")"
-            folderName="$(basename "${path%"/."}")"
+            relPath=${path#"$inFolder/"}
+            folderPath="$(dirname "$relPath")"
+            folderName="$(basename "$relPath")"
         fi
 
         oldPath=$PWD
-        cd "$inFolder/$path"
+        cd "$path"
 
         findCommand="find \".\""
         if [ "$_arg_all" = "off" ]; then
@@ -123,13 +124,14 @@ function handleDir {
         fi
         findCommand+=" ! -name \".\" ! -name \"decrypt.sh\" ! -name \"pgpbackup-decrypt\" -type f"
 
-        if [ ! -d "$oldPath/$tmpFolder/$folderPath" ]; then
-            mkdir "$oldPath/$tmpFolder/$folderPath"
+        folderPathInTmp=$(validifyVirtualLink "$tmpFolder/$folderPath")
+        if [ ! -d "$folderPathInTmp" ]; then
+            mkdir "$folderPathInTmp"
         fi
         local zippedBytes=0
         while read i
         do
-            command="zip -qur \"$oldPath/$tmpFolder/$folderPath/$folderName.pb.zip\" \"${i#"$inFolder/"}\""
+            command="zip -qur \"$folderPathInTmp/$folderName.pb.zip\" \"${i#"$inFolder/"}\""
             execute "$command"
 
             local filesize=$(stat --printf="%s" "${i#"$inFolder/"}")
@@ -139,21 +141,23 @@ function handleDir {
         done <<< $(eval $findCommand)
         cd "$oldPath"
 
-        if [ "$path" == "." ]; then
+        if [ $first = "on" ]; then
             path=$folderName
         fi
-        if [ -f "$tmpFolder/${path%"/."}.pb.zip" ]; then
-            encryptFile "$tmpFolder/${path%"/."}.pb.zip" "$outFolder/${path%"/."}.zip"
-            rm "$tmpFolder/${path%"/."}.pb.zip"
+
+        tmpFilePath=$(validifyLink "$tmpFolder/${path#"$inFolder/"}")
+        if [ -f "$tmpFilePath.pb.zip" ]; then
+            encryptFile "$tmpFilePath.pb.zip" "$outFolder/${path#"$inFolder/"}.zip"
+            rm "$tmpFilePath.pb.zip"
 
             addToProgress $zippedBytes
         else
-            >&2 echo "Error: $tmpFolder/${path%"/."}.pb.zip not found! (This is probably a programming error)"
+            >&2 echo "Error: $tmpFilePath.pb.zip not found! (This is probably a programming error)"
             rm -r "$tmpFolder"
             exit 1
         fi
     else
-        if [ "$path" != "$inFolder" ]; then
+        if [ "$first" = "off" ]; then
             mkdir "$outFolder/"${path#"$inFolder"}
             mkdir "$tmpFolder/"${path#"$inFolder"}
         fi
@@ -172,9 +176,9 @@ function handleDir {
         eval $findCommand | while read i
         do
             if [ $depth -gt 0 ]; then
-                handleDir $[$depth-1] "$i"
+                handleDir $[depth - 1] "$i" "off"
             elif [ $depth -lt 0 ]; then
-                handleDir $depth "$i"
+                handleDir $depth "$i" "off"
             fi
         done
     fi
@@ -259,7 +263,7 @@ if [ -d "$outFolder" ]; then
     fi
 fi
 
-handleDir $depth $email $inFolder
+handleDir $depth $email $inFolder "on"
 
 printLogN "Finished encrypting!"
 
@@ -271,7 +275,6 @@ if [ "$_arg_name_hashing" = "on" ]; then
     createOverviewFile "$outFolder" 0 "$overviewFile"
 
     # Hash file names
-    local i
     find "$outFolder" -depth -iname "*.gpg" -type f | while read i
     do
         # Hash filename
@@ -279,7 +282,6 @@ if [ "$_arg_name_hashing" = "on" ]; then
     done
 
     # Hash folder names
-    local j
     find "$outFolder" -mindepth 1 -depth -type d | while read j
     do
         path="$(dirname "$j")"
